version: '3.7'
services:
  bandla-app:
    build:
      context: .
    container_name: match-making
    image: nazarovv2/match-making:latest
    ports:
      - "80:80"
    networks:
      - net
networks:
  net:
    driver: "bridge"